export const RAW_PAGES = [
{
  "id": "1.0",
  "pageTitle": "Emergency Septic Pumping in Canada | 24/7 Same Day, Call Now",
  "pageSlug": "/emergency-septic-pumping",
  "primaryKeyword": "emergency septic pumping",
  "secondaryKeywords": "24 7 septic pumping, emergency septic tank services, emergency septic tank service, emergency septic pumping near me, emergency septic service",
  "targetArea": "Canada (National)",
  "pageType": "Emergency",
  "searchIntent": "Transactional",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "2.0",
  "pageTitle": "Emergency Sump Pump Repair | 24 Hour Service Across Canada",
  "pageSlug": "/emergency-sump-pump-repair",
  "primaryKeyword": "emergency sump pump repair",
  "secondaryKeywords": "24 hour sump pump repair, emergency sump pump repair near me, sump pump emergency, after hours sump pump repair",
  "targetArea": "Canada (National)",
  "pageType": "Emergency",
  "searchIntent": "Transactional",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "0.8",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "3.0",
  "pageTitle": "Sump Pump Not Working? | Fast Repair, Call 24/7",
  "pageSlug": "/sump-pump-not-working",
  "primaryKeyword": "sump pump not working",
  "secondaryKeywords": "sump pump not pumping water, sump pump wont turn on, sump pump keeps running, sump pump stopped working",
  "targetArea": "Canada (National)",
  "pageType": "Symptom",
  "searchIntent": "Informational",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "4.0",
  "pageTitle": "Septic Tank Pumping in Canada | Fast, Reliable, Call Today",
  "pageSlug": "/septic-tank-pumping",
  "primaryKeyword": "septic tank pumping",
  "secondaryKeywords": "septic pumping, septic tank pumping service, septic system pumping, septic pumping services",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "2300.0",
  "keywordDifficulty": "3.0",
  "cpc": "2.5",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "5.0",
  "pageTitle": "Septic Pumping Near Me | Local Pros, Same Day Service",
  "pageSlug": "/septic-pumping-near-me",
  "primaryKeyword": "septic pumping near me",
  "secondaryKeywords": "septic tank pumping near me, septic pumping service near me, septic pumping services near me, septic system pumping near me",
  "targetArea": "Canada (National)",
  "pageType": "Near Me",
  "searchIntent": "Transactional",
  "volumePerMonth": "1900.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.0",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "6.0",
  "pageTitle": "Septic Tank Cleaning in Canada | Trusted Local Cleaners",
  "pageSlug": "/septic-tank-cleaning",
  "primaryKeyword": "septic tank cleaning",
  "secondaryKeywords": "septic cleaning, septic system cleaning, septic cleaning services, septic tank cleaning services, septic tank cleaning service",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "1600.0",
  "keywordDifficulty": "9.0",
  "cpc": "1.6",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "7.0",
  "pageTitle": "Septic Tank Cleaning Near Me | Book Local Service Fast",
  "pageSlug": "/septic-tank-cleaning-near-me",
  "primaryKeyword": "septic tank cleaning near me",
  "secondaryKeywords": "septic cleaning near me, septic system cleaning near me, septic tank cleaning service near me",
  "targetArea": "Canada (National)",
  "pageType": "Near Me",
  "searchIntent": "Transactional",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "1.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "8.0",
  "pageTitle": "Septic Tank Repair in Canada | Leaks, Baffles, Alarms Fixed",
  "pageSlug": "/septic-tank-repair",
  "primaryKeyword": "septic tank repair",
  "secondaryKeywords": "septic tank repair near me, septic tank divider wall repair, septic tank alarm repair, septic tank leak repair, septic tank baffle repair",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "900.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "9.0",
  "pageTitle": "Septic Services in Canada | Pumping, Cleaning, Repair",
  "pageSlug": "/septic-services",
  "primaryKeyword": "septic services near me",
  "secondaryKeywords": "septic services, septic service near me, septic tank service near me, septic tank services, septic system service",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "450.0",
  "keywordDifficulty": "33.0",
  "cpc": "2.0",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "10.0",
  "pageTitle": "Septic Pump Replacement and Repair | Effluent Pump Pros",
  "pageSlug": "/septic-pump-replacement",
  "primaryKeyword": "septic pump replacement",
  "secondaryKeywords": "septic pump repair, septic pump repair near me, septic effluent pump replacement, septic lift pump replacement",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "11.0",
  "pageTitle": "RV and Holding Tank Pumping in Canada | Mobile Service",
  "pageSlug": "/rv-holding-tank-pumping",
  "primaryKeyword": "rv septic tank cleaning",
  "secondaryKeywords": "rv septic service, holding tank pumping, rv holding tank pump out, portable tank pumping",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "160.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "12.0",
  "pageTitle": "Septic Tank Cleaning Cost in Canada | Pricing Guide",
  "pageSlug": "/septic-tank-cleaning-cost",
  "primaryKeyword": "septic tank cleaning cost",
  "secondaryKeywords": "septic tank pumping cost, septic tank emptying cost, cost of emptying septic tank, how much to pump a septic tank",
  "targetArea": "Canada (National)",
  "pageType": "Cost Guide",
  "searchIntent": "Commercial",
  "volumePerMonth": "120.0",
  "keywordDifficulty": "6.0",
  "cpc": "1.2",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "13.0",
  "pageTitle": "Sump Pump Installation in Canada | Licensed, Same Week",
  "pageSlug": "/sump-pump-installation",
  "primaryKeyword": "sump pump installation",
  "secondaryKeywords": "sump pump installation near me, basement sump pump installation, sump pump install, backup sump pump installation, sump pump discharge pipe installation",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "2800.0",
  "keywordDifficulty": "3.0",
  "cpc": "1.8",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "14.0",
  "pageTitle": "Sump Pump Repair in Canada | Fast, Affordable, Call Now",
  "pageSlug": "/sump-pump-repair",
  "primaryKeyword": "sump pump repair",
  "secondaryKeywords": "sump pump repair near me, plumber sump pump repair, basement sump pump repair, residential sump pump repair",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "1800.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "15.0",
  "pageTitle": "Sump Pump Replacement in Canada | Upgrade and Save",
  "pageSlug": "/sump-pump-replacement",
  "primaryKeyword": "sump pump replacement",
  "secondaryKeywords": "sump pump replacement near me, replace sump pump, sump pump swap, old sump pump replacement",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "500.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.6",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "16.0",
  "pageTitle": "Sump Pump Repair Near Me | Local Pros, Same Day",
  "pageSlug": "/sump-pump-repair-near-me",
  "primaryKeyword": "sump pump repair near me",
  "secondaryKeywords": "sump pump service near me, sump pump replacement near me, sump pump installation near me",
  "targetArea": "Canada (National)",
  "pageType": "Near Me",
  "searchIntent": "Transactional",
  "volumePerMonth": "250.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "17.0",
  "pageTitle": "Sump Pump Service in Canada | Repair, Maintenance, Install",
  "pageSlug": "/sump-pump-service",
  "primaryKeyword": "sump pump service",
  "secondaryKeywords": "sump pump maintenance, sump pump tune up, sump pump inspection, annual sump pump service",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "0.0",
  "cpc": "6.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "18.0",
  "pageTitle": "Commercial Sump Pump Repair | Industrial and Business Sites",
  "pageSlug": "/commercial-sump-pump-repair",
  "primaryKeyword": "commercial sump pump repair",
  "secondaryKeywords": "commercial sump pump service, industrial sump pump repair, commercial sump pump installation, building sump pump repair",
  "targetArea": "Canada (National)",
  "pageType": "Service Pillar",
  "searchIntent": "Transactional",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "19.0",
  "pageTitle": "Sump Pump Replacement and Installation Cost in Canada",
  "pageSlug": "/sump-pump-replacement-cost",
  "primaryKeyword": "sump pump replacement cost",
  "secondaryKeywords": "sump pump installation cost, sump pump cost canada, sump pump installation cost canada, sump pump replacement cost canada",
  "targetArea": "Canada (National)",
  "pageType": "Cost Guide",
  "searchIntent": "Commercial",
  "volumePerMonth": "650.0",
  "keywordDifficulty": "1.0",
  "cpc": "1.8",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "20.0",
  "pageTitle": "Septic Tank Pumping Kelowna | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-kelowna",
  "primaryKeyword": "septic tank pumping kelowna",
  "secondaryKeywords": "septic pumping kelowna, septic tank cleaning kelowna, septic tank repair kelowna, septic service kelowna",
  "targetArea": "Kelowna, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "250.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "21.0",
  "pageTitle": "Septic Pumping Penticton | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-penticton",
  "primaryKeyword": "septic pumping penticton",
  "secondaryKeywords": "septic tank pumping penticton, septic tank cleaning penticton, septic tank repair penticton, septic service penticton",
  "targetArea": "Penticton, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "22.0",
  "pageTitle": "Septic Pumping Vernon | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-vernon",
  "primaryKeyword": "septic pumping vernon",
  "secondaryKeywords": "septic tank pumping vernon, septic tank cleaning vernon, septic tank repair vernon, septic service vernon",
  "targetArea": "Vernon, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "23.0",
  "pageTitle": "Septic Pumping Kamloops | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-kamloops",
  "primaryKeyword": "septic pumping kamloops",
  "secondaryKeywords": "septic tank pumping kamloops, septic tank cleaning kamloops, septic tank repair kamloops, septic service kamloops",
  "targetArea": "Kamloops, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "24.0",
  "pageTitle": "Septic Pumping West Kelowna | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-west-kelowna",
  "primaryKeyword": "septic pumping west kelowna",
  "secondaryKeywords": "septic tank pumping west kelowna, septic tank cleaning west kelowna, septic tank repair west kelowna, septic service west kelowna",
  "targetArea": "West Kelowna, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "3.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "25.0",
  "pageTitle": "Septic Pumping Summerland | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-summerland",
  "primaryKeyword": "septic pumping summerland",
  "secondaryKeywords": "septic tank pumping summerland, septic tank cleaning summerland, septic tank repair summerland, septic service summerland",
  "targetArea": "Summerland, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "3.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "26.0",
  "pageTitle": "Septic Pumping Armstrong | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-armstrong",
  "primaryKeyword": "septic pumping armstrong",
  "secondaryKeywords": "septic tank pumping armstrong, septic tank cleaning armstrong, septic tank repair armstrong, septic service armstrong",
  "targetArea": "Armstrong, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "3.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "27.0",
  "pageTitle": "Septic Pumping Lake Country | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-lake-country",
  "primaryKeyword": "septic pumping lake country",
  "secondaryKeywords": "septic tank pumping lake country, septic tank cleaning lake country, septic tank repair lake country, septic service lake country",
  "targetArea": "Lake Country, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "3.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "28.0",
  "pageTitle": "Septic Pumping Peachland | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-peachland",
  "primaryKeyword": "septic pumping peachland",
  "secondaryKeywords": "septic tank pumping peachland, septic tank cleaning peachland, septic tank repair peachland, septic service peachland",
  "targetArea": "Peachland, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "3.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "29.0",
  "pageTitle": "Septic Tank Pumping Salmon Arm | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-salmon-arm",
  "primaryKeyword": "septic tank pumping salmon arm",
  "secondaryKeywords": "septic pumping salmon arm, septic tank cleaning salmon arm, septic tank repair salmon arm, septic service salmon arm",
  "targetArea": "Salmon Arm, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "30.0",
  "pageTitle": "Septic Tank Pumping Osoyoos | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-osoyoos",
  "primaryKeyword": "septic tank pumping osoyoos",
  "secondaryKeywords": "septic pumping osoyoos, septic tank cleaning osoyoos, septic tank repair osoyoos, septic service osoyoos",
  "targetArea": "Osoyoos, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "31.0",
  "pageTitle": "Septic Tank Pumping Oliver | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-oliver",
  "primaryKeyword": "septic tank pumping oliver",
  "secondaryKeywords": "septic pumping oliver, septic tank cleaning oliver, septic tank repair oliver, septic service oliver",
  "targetArea": "Oliver, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "32.0",
  "pageTitle": "Septic Tank Pumping Merritt | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-merritt",
  "primaryKeyword": "septic tank pumping merritt",
  "secondaryKeywords": "septic pumping merritt, septic tank cleaning merritt, septic tank repair merritt, septic service merritt",
  "targetArea": "Merritt, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "33.0",
  "pageTitle": "Septic Tank Cleaning Langley | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-langley",
  "primaryKeyword": "septic tank cleaning langley",
  "secondaryKeywords": "septic tank pumping langley, septic pumping langley, septic tank repair langley, septic service langley",
  "targetArea": "Langley, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "8.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "34.0",
  "pageTitle": "Septic Tank Cleaning Surrey | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-surrey",
  "primaryKeyword": "septic tank cleaning surrey",
  "secondaryKeywords": "septic tank pumping surrey, septic pumping surrey, septic tank repair surrey, septic service surrey",
  "targetArea": "Surrey, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "35.0",
  "pageTitle": "Septic Tank Cleaning Maple Ridge | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-maple-ridge",
  "primaryKeyword": "septic tank cleaning maple ridge",
  "secondaryKeywords": "septic tank pumping maple ridge, septic pumping maple ridge, septic tank repair maple ridge, septic service maple ridge",
  "targetArea": "Maple Ridge, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "36.0",
  "pageTitle": "Septic Tank Cleaning Chilliwack | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-chilliwack",
  "primaryKeyword": "septic tank cleaning chilliwack",
  "secondaryKeywords": "septic tank pumping chilliwack, septic pumping chilliwack, septic tank repair chilliwack, septic service chilliwack",
  "targetArea": "Chilliwack, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "18.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "37.0",
  "pageTitle": "Septic Tank Cleaning Abbotsford | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-abbotsford",
  "primaryKeyword": "septic tank cleaning abbotsford",
  "secondaryKeywords": "septic tank pumping abbotsford, septic pumping abbotsford, septic tank repair abbotsford, septic service abbotsford",
  "targetArea": "Abbotsford, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "22.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "38.0",
  "pageTitle": "Septic Tank Pumping Victoria | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-victoria",
  "primaryKeyword": "septic tank pumping victoria",
  "secondaryKeywords": "septic pumping victoria, septic tank cleaning victoria, septic tank repair victoria, septic service victoria",
  "targetArea": "Victoria, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "39.0",
  "pageTitle": "Septic Tank Cleaning Vancouver | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-vancouver",
  "primaryKeyword": "septic tank cleaning vancouver",
  "secondaryKeywords": "septic tank pumping vancouver, septic pumping vancouver, septic tank repair vancouver, septic service vancouver",
  "targetArea": "Vancouver, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "5.0",
  "cpc": "1.6",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "40.0",
  "pageTitle": "Septic Tank Cleaning Burnaby | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-burnaby",
  "primaryKeyword": "septic tank cleaning burnaby",
  "secondaryKeywords": "septic tank pumping burnaby, septic pumping burnaby, septic tank repair burnaby, septic service burnaby",
  "targetArea": "Burnaby, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "41.0",
  "pageTitle": "Septic Tank Cleaning Mission | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-mission",
  "primaryKeyword": "septic tank cleaning mission",
  "secondaryKeywords": "septic tank pumping mission, septic pumping mission, septic tank repair mission, septic service mission",
  "targetArea": "Mission, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "42.0",
  "pageTitle": "Septic Tank Cleaning Hope | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-hope",
  "primaryKeyword": "septic tank cleaning hope",
  "secondaryKeywords": "septic tank pumping hope, septic pumping hope, septic tank repair hope, septic service hope",
  "targetArea": "Hope, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "43.0",
  "pageTitle": "Septic Tank Pumping Nanaimo | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-nanaimo",
  "primaryKeyword": "septic tank pumping nanaimo",
  "secondaryKeywords": "septic pumping nanaimo, septic tank cleaning nanaimo, septic tank repair nanaimo, septic service nanaimo",
  "targetArea": "Nanaimo, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "44.0",
  "pageTitle": "Septic Tank Pumping Courtenay | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-courtenay",
  "primaryKeyword": "septic tank pumping courtenay",
  "secondaryKeywords": "septic pumping courtenay, septic tank cleaning courtenay, septic tank repair courtenay, septic service courtenay",
  "targetArea": "Courtenay, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "45.0",
  "pageTitle": "Septic Tank Pumping Duncan | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-duncan",
  "primaryKeyword": "septic tank pumping duncan",
  "secondaryKeywords": "septic pumping duncan, septic tank cleaning duncan, septic tank repair duncan, septic service duncan",
  "targetArea": "Duncan, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "46.0",
  "pageTitle": "Septic Tank Pumping Sechelt | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-sechelt",
  "primaryKeyword": "septic tank pumping sechelt",
  "secondaryKeywords": "septic pumping sechelt, septic tank cleaning sechelt, septic tank repair sechelt, septic service sechelt",
  "targetArea": "Sechelt, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "47.0",
  "pageTitle": "Septic Tank Pumping Ottawa | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-ottawa",
  "primaryKeyword": "septic tank pumping ottawa",
  "secondaryKeywords": "septic pumping ottawa, septic tank cleaning ottawa, septic tank repair ottawa, septic service ottawa",
  "targetArea": "Ottawa, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "24.0",
  "cpc": "1.1",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "48.0",
  "pageTitle": "Septic Tank Repair Belleville | Pumping and Repair Service",
  "pageSlug": "/septic-tank-repair-belleville",
  "primaryKeyword": "septic tank repair belleville",
  "secondaryKeywords": "septic tank pumping belleville, septic pumping belleville, septic tank cleaning belleville, septic service belleville",
  "targetArea": "Belleville, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "5.0",
  "cpc": "1.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "49.0",
  "pageTitle": "Septic Tank Pumping Kingston | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-kingston",
  "primaryKeyword": "septic tank pumping kingston",
  "secondaryKeywords": "septic pumping kingston, septic tank cleaning kingston, septic tank repair kingston, septic service kingston",
  "targetArea": "Kingston, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "50.0",
  "pageTitle": "Septic Tank Pumping Collingwood | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-collingwood",
  "primaryKeyword": "septic tank pumping collingwood",
  "secondaryKeywords": "septic pumping collingwood, septic tank cleaning collingwood, septic tank repair collingwood, septic service collingwood",
  "targetArea": "Collingwood, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "51.0",
  "pageTitle": "Septic Pumping Thunder Bay | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-thunder-bay",
  "primaryKeyword": "septic pumping thunder bay",
  "secondaryKeywords": "septic tank pumping thunder bay, septic tank cleaning thunder bay, septic tank repair thunder bay, septic service thunder bay",
  "targetArea": "Thunder Bay, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "1.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "52.0",
  "pageTitle": "Septic Tank Pumping Leamington | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-leamington",
  "primaryKeyword": "septic tank pumping leamington",
  "secondaryKeywords": "septic pumping leamington, septic tank cleaning leamington, septic tank repair leamington, septic service leamington",
  "targetArea": "Leamington, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "53.0",
  "pageTitle": "Septic Tank Pumping Hamilton | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-hamilton",
  "primaryKeyword": "septic tank pumping hamilton",
  "secondaryKeywords": "septic pumping hamilton, septic tank cleaning hamilton, septic tank repair hamilton, septic service hamilton",
  "targetArea": "Hamilton, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "54.0",
  "pageTitle": "Septic Tank Pumping Sault Ste Marie | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-sault-ste-marie",
  "primaryKeyword": "septic tank pumping sault ste marie",
  "secondaryKeywords": "septic pumping sault ste marie, septic tank cleaning sault ste marie, septic tank repair sault ste marie, septic service sault ste marie",
  "targetArea": "Sault Ste Marie, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "55.0",
  "pageTitle": "Septic Pumping Caledonia | Local Tank Pumping Service, Call Today",
  "pageSlug": "/septic-pumping-caledonia",
  "primaryKeyword": "septic pumping caledonia",
  "secondaryKeywords": "septic tank pumping caledonia, septic tank cleaning caledonia, septic tank repair caledonia, septic service caledonia",
  "targetArea": "Caledonia, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "56.0",
  "pageTitle": "Septic Tank Pumping Stayner | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-stayner",
  "primaryKeyword": "septic tank pumping stayner",
  "secondaryKeywords": "septic pumping stayner, septic tank cleaning stayner, septic tank repair stayner, septic service stayner",
  "targetArea": "Stayner, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "57.0",
  "pageTitle": "Septic Tank Pumping Angus | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-angus",
  "primaryKeyword": "septic tank pumping angus",
  "secondaryKeywords": "septic pumping angus, septic tank cleaning angus, septic tank repair angus, septic service angus",
  "targetArea": "Angus, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "58.0",
  "pageTitle": "Septic Tank Pumping Wasaga Beach | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-wasaga-beach",
  "primaryKeyword": "septic tank pumping wasaga beach",
  "secondaryKeywords": "septic pumping wasaga beach, septic tank cleaning wasaga beach, septic tank repair wasaga beach, septic service wasaga beach",
  "targetArea": "Wasaga Beach, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "59.0",
  "pageTitle": "Septic Tank Pumping Orillia | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-orillia",
  "primaryKeyword": "septic tank pumping orillia",
  "secondaryKeywords": "septic pumping orillia, septic tank cleaning orillia, septic tank repair orillia, septic service orillia",
  "targetArea": "Orillia, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "60.0",
  "pageTitle": "Septic Tank Pumping Midland | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-midland",
  "primaryKeyword": "septic tank pumping midland",
  "secondaryKeywords": "septic pumping midland, septic tank cleaning midland, septic tank repair midland, septic service midland",
  "targetArea": "Midland, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "61.0",
  "pageTitle": "Septic Tank Pumping Shelburne | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-shelburne",
  "primaryKeyword": "septic tank pumping shelburne",
  "secondaryKeywords": "septic pumping shelburne, septic tank cleaning shelburne, septic tank repair shelburne, septic service shelburne",
  "targetArea": "Shelburne, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "62.0",
  "pageTitle": "Septic Tank Pumping Bracebridge | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-bracebridge",
  "primaryKeyword": "septic tank pumping bracebridge",
  "secondaryKeywords": "septic pumping bracebridge, septic tank cleaning bracebridge, septic tank repair bracebridge, septic service bracebridge",
  "targetArea": "Bracebridge, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "63.0",
  "pageTitle": "Septic Tank Pumping Huntsville | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-huntsville",
  "primaryKeyword": "septic tank pumping huntsville",
  "secondaryKeywords": "septic pumping huntsville, septic tank cleaning huntsville, septic tank repair huntsville, septic service huntsville",
  "targetArea": "Huntsville, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "64.0",
  "pageTitle": "Septic Tank Pumping Parry Sound | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-parry-sound",
  "primaryKeyword": "septic tank pumping parry sound",
  "secondaryKeywords": "septic pumping parry sound, septic tank cleaning parry sound, septic tank repair parry sound, septic service parry sound",
  "targetArea": "Parry Sound, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "65.0",
  "pageTitle": "Septic Tank Pumping Peterborough | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-peterborough",
  "primaryKeyword": "septic tank pumping peterborough",
  "secondaryKeywords": "septic pumping peterborough, septic tank cleaning peterborough, septic tank repair peterborough, septic service peterborough",
  "targetArea": "Peterborough, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "66.0",
  "pageTitle": "Septic Tank Pumping Lindsay | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-lindsay",
  "primaryKeyword": "septic tank pumping lindsay",
  "secondaryKeywords": "septic pumping lindsay, septic tank cleaning lindsay, septic tank repair lindsay, septic service lindsay",
  "targetArea": "Lindsay, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "67.0",
  "pageTitle": "Septic Tank Pumping Bancroft | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-bancroft",
  "primaryKeyword": "septic tank pumping bancroft",
  "secondaryKeywords": "septic pumping bancroft, septic tank cleaning bancroft, septic tank repair bancroft, septic service bancroft",
  "targetArea": "Bancroft, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "68.0",
  "pageTitle": "Septic Tank Pumping North Bay | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-north-bay",
  "primaryKeyword": "septic tank pumping north bay",
  "secondaryKeywords": "septic pumping north bay, septic tank cleaning north bay, septic tank repair north bay, septic service north bay",
  "targetArea": "North Bay, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "69.0",
  "pageTitle": "Septic Tank Pumping Sudbury | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-sudbury",
  "primaryKeyword": "septic tank pumping sudbury",
  "secondaryKeywords": "septic pumping sudbury, septic tank cleaning sudbury, septic tank repair sudbury, septic service sudbury",
  "targetArea": "Sudbury, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "70.0",
  "pageTitle": "Septic Tank Pumping Cornwall | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-cornwall",
  "primaryKeyword": "septic tank pumping cornwall",
  "secondaryKeywords": "septic pumping cornwall, septic tank cleaning cornwall, septic tank repair cornwall, septic service cornwall",
  "targetArea": "Cornwall, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "71.0",
  "pageTitle": "Septic Tank Pumping Pembroke | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-pembroke",
  "primaryKeyword": "septic tank pumping pembroke",
  "secondaryKeywords": "septic pumping pembroke, septic tank cleaning pembroke, septic tank repair pembroke, septic service pembroke",
  "targetArea": "Pembroke, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "72.0",
  "pageTitle": "Septic Tank Pumping Carleton Place | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-carleton-place",
  "primaryKeyword": "septic tank pumping carleton place",
  "secondaryKeywords": "septic pumping carleton place, septic tank cleaning carleton place, septic tank repair carleton place, septic service carleton place",
  "targetArea": "Carleton Place, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "73.0",
  "pageTitle": "Septic Tank Pumping Kemptville | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-kemptville",
  "primaryKeyword": "septic tank pumping kemptville",
  "secondaryKeywords": "septic pumping kemptville, septic tank cleaning kemptville, septic tank repair kemptville, septic service kemptville",
  "targetArea": "Kemptville, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "74.0",
  "pageTitle": "Septic Tank Pumping Calgary | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-calgary",
  "primaryKeyword": "septic tank pumping calgary",
  "secondaryKeywords": "septic pumping calgary, septic tank cleaning calgary, septic tank repair calgary, septic service calgary",
  "targetArea": "Calgary, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "15.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "75.0",
  "pageTitle": "Septic Tank Repair Edmonton | Pumping and Repair Service",
  "pageSlug": "/septic-tank-repair-edmonton",
  "primaryKeyword": "septic tank repair edmonton",
  "secondaryKeywords": "septic tank pumping edmonton, septic pumping edmonton, septic tank cleaning edmonton, septic service edmonton",
  "targetArea": "Edmonton, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "5.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "76.0",
  "pageTitle": "Septic Tank Cleaning Vulcan | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-vulcan",
  "primaryKeyword": "septic tank cleaning vulcan",
  "secondaryKeywords": "septic tank pumping vulcan, septic pumping vulcan, septic tank repair vulcan, septic service vulcan",
  "targetArea": "Vulcan, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "77.0",
  "pageTitle": "Septic Tank Pumping Sherwood Park | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-sherwood-park",
  "primaryKeyword": "septic tank pumping sherwood park",
  "secondaryKeywords": "septic pumping sherwood park, septic tank cleaning sherwood park, septic tank repair sherwood park, septic service sherwood park",
  "targetArea": "Sherwood Park, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "78.0",
  "pageTitle": "Septic Tank Pumping Red Deer | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-red-deer",
  "primaryKeyword": "septic tank pumping red deer",
  "secondaryKeywords": "septic pumping red deer, septic tank cleaning red deer, septic tank repair red deer, septic service red deer",
  "targetArea": "Red Deer, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "79.0",
  "pageTitle": "Septic Tank Pumping Airdrie | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-airdrie",
  "primaryKeyword": "septic tank pumping airdrie",
  "secondaryKeywords": "septic pumping airdrie, septic tank cleaning airdrie, septic tank repair airdrie, septic service airdrie",
  "targetArea": "Airdrie, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "80.0",
  "pageTitle": "Septic Tank Pumping Okotoks | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-okotoks",
  "primaryKeyword": "septic tank pumping okotoks",
  "secondaryKeywords": "septic pumping okotoks, septic tank cleaning okotoks, septic tank repair okotoks, septic service okotoks",
  "targetArea": "Okotoks, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "81.0",
  "pageTitle": "Septic Tank Pumping Cochrane | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-cochrane",
  "primaryKeyword": "septic tank pumping cochrane",
  "secondaryKeywords": "septic pumping cochrane, septic tank cleaning cochrane, septic tank repair cochrane, septic service cochrane",
  "targetArea": "Cochrane, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "82.0",
  "pageTitle": "Septic Tank Pumping Lethbridge | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-lethbridge",
  "primaryKeyword": "septic tank pumping lethbridge",
  "secondaryKeywords": "septic pumping lethbridge, septic tank cleaning lethbridge, septic tank repair lethbridge, septic service lethbridge",
  "targetArea": "Lethbridge, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "83.0",
  "pageTitle": "Septic Tank Pumping Medicine Hat | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-medicine-hat",
  "primaryKeyword": "septic tank pumping medicine hat",
  "secondaryKeywords": "septic pumping medicine hat, septic tank cleaning medicine hat, septic tank repair medicine hat, septic service medicine hat",
  "targetArea": "Medicine Hat, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "84.0",
  "pageTitle": "Septic Tank Pumping Grande Prairie | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-grande-prairie",
  "primaryKeyword": "septic tank pumping grande prairie",
  "secondaryKeywords": "septic pumping grande prairie, septic tank cleaning grande prairie, septic tank repair grande prairie, septic service grande prairie",
  "targetArea": "Grande Prairie, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "85.0",
  "pageTitle": "Septic Tank Pumping Spruce Grove | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-spruce-grove",
  "primaryKeyword": "septic tank pumping spruce grove",
  "secondaryKeywords": "septic pumping spruce grove, septic tank cleaning spruce grove, septic tank repair spruce grove, septic service spruce grove",
  "targetArea": "Spruce Grove, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "86.0",
  "pageTitle": "Septic Tank Pumping Saskatoon | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-saskatoon",
  "primaryKeyword": "septic tank pumping saskatoon",
  "secondaryKeywords": "septic pumping saskatoon, septic tank cleaning saskatoon, septic tank repair saskatoon, septic service saskatoon",
  "targetArea": "Saskatoon, SK",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "87.0",
  "pageTitle": "Septic Tank Pumping Regina | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-regina",
  "primaryKeyword": "septic tank pumping regina",
  "secondaryKeywords": "septic pumping regina, septic tank cleaning regina, septic tank repair regina, septic service regina",
  "targetArea": "Regina, SK",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "88.0",
  "pageTitle": "Septic Tank Pumping Prince Albert | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-prince-albert",
  "primaryKeyword": "septic tank pumping prince albert",
  "secondaryKeywords": "septic pumping prince albert, septic tank cleaning prince albert, septic tank repair prince albert, septic service prince albert",
  "targetArea": "Prince Albert, SK",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "89.0",
  "pageTitle": "Septic Tank Pumping Moose Jaw | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-moose-jaw",
  "primaryKeyword": "septic tank pumping moose jaw",
  "secondaryKeywords": "septic pumping moose jaw, septic tank cleaning moose jaw, septic tank repair moose jaw, septic service moose jaw",
  "targetArea": "Moose Jaw, SK",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "90.0",
  "pageTitle": "Septic Tank Pumping Brandon | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-brandon",
  "primaryKeyword": "septic tank pumping brandon",
  "secondaryKeywords": "septic pumping brandon, septic tank cleaning brandon, septic tank repair brandon, septic service brandon",
  "targetArea": "Brandon, MB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "91.0",
  "pageTitle": "Septic Tank Pumping Steinbach | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-steinbach",
  "primaryKeyword": "septic tank pumping steinbach",
  "secondaryKeywords": "septic pumping steinbach, septic tank cleaning steinbach, septic tank repair steinbach, septic service steinbach",
  "targetArea": "Steinbach, MB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "92.0",
  "pageTitle": "Septic Tank Pumping Selkirk | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-selkirk",
  "primaryKeyword": "septic tank pumping selkirk",
  "secondaryKeywords": "septic pumping selkirk, septic tank cleaning selkirk, septic tank repair selkirk, septic service selkirk",
  "targetArea": "Selkirk, MB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "93.0",
  "pageTitle": "Septic Tank Pumping Winnipeg | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-winnipeg",
  "primaryKeyword": "septic tank pumping winnipeg",
  "secondaryKeywords": "septic pumping winnipeg, septic tank cleaning winnipeg, septic tank repair winnipeg, septic service winnipeg",
  "targetArea": "Winnipeg, MB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.8",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "94.0",
  "pageTitle": "Septic Tank Cleaning Fredericton | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-fredericton",
  "primaryKeyword": "septic tank cleaning fredericton",
  "secondaryKeywords": "septic tank pumping fredericton, septic pumping fredericton, septic tank repair fredericton, septic service fredericton",
  "targetArea": "Fredericton, NB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "4.0",
  "cpc": "1.4",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "95.0",
  "pageTitle": "Septic Tank Cleaning Sussex | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-sussex",
  "primaryKeyword": "septic tank cleaning sussex",
  "secondaryKeywords": "septic tank pumping sussex, septic pumping sussex, septic tank repair sussex, septic service sussex",
  "targetArea": "Sussex, NB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "96.0",
  "pageTitle": "Septic Tank Cleaning Moncton | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-moncton",
  "primaryKeyword": "septic tank cleaning moncton",
  "secondaryKeywords": "septic tank pumping moncton, septic pumping moncton, septic tank repair moncton, septic service moncton",
  "targetArea": "Moncton, NB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "97.0",
  "pageTitle": "Septic Tank Cleaning Saint John | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-saint-john",
  "primaryKeyword": "septic tank cleaning saint john",
  "secondaryKeywords": "septic tank pumping saint john, septic pumping saint john, septic tank repair saint john, septic service saint john",
  "targetArea": "Saint John, NB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "98.0",
  "pageTitle": "Septic Tank Pumping Halifax | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-halifax",
  "primaryKeyword": "septic tank pumping halifax",
  "secondaryKeywords": "septic pumping halifax, septic tank cleaning halifax, septic tank repair halifax, septic service halifax",
  "targetArea": "Halifax, NS",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "80.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.6",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "99.0",
  "pageTitle": "Septic Tank Pumping Truro | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-truro",
  "primaryKeyword": "septic tank pumping truro",
  "secondaryKeywords": "septic pumping truro, septic tank cleaning truro, septic tank repair truro, septic service truro",
  "targetArea": "Truro, NS",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "100.0",
  "pageTitle": "Septic Tank Pumping Charlottetown | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-charlottetown",
  "primaryKeyword": "septic tank pumping charlottetown",
  "secondaryKeywords": "septic pumping charlottetown, septic tank cleaning charlottetown, septic tank repair charlottetown, septic service charlottetown",
  "targetArea": "Charlottetown, PE",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "101.0",
  "pageTitle": "Septic Tank Pumping St Johns | Fast Local Service, Call Now",
  "pageSlug": "/septic-tank-pumping-st-johns",
  "primaryKeyword": "septic tank pumping st johns",
  "secondaryKeywords": "septic pumping st johns, septic tank cleaning st johns, septic tank repair st johns, septic service st johns",
  "targetArea": "St Johns, NL",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "102.0",
  "pageTitle": "Septic Tank Cleaning Gatineau | Pumping and Cleaning Pros",
  "pageSlug": "/septic-tank-cleaning-gatineau",
  "primaryKeyword": "septic tank cleaning gatineau",
  "secondaryKeywords": "septic tank pumping gatineau, septic pumping gatineau, septic tank repair gatineau, septic service gatineau",
  "targetArea": "Gatineau, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.5",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "103.0",
  "pageTitle": "Sump Pump Installation Toronto | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-toronto",
  "primaryKeyword": "sump pump installation toronto",
  "secondaryKeywords": "sump pump repair toronto, sump pump replacement toronto, sump pump service toronto",
  "targetArea": "Toronto, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "350.0",
  "keywordDifficulty": "0.0",
  "cpc": "9.0",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "104.0",
  "pageTitle": "Sump Pump Installation Oakville | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-oakville",
  "primaryKeyword": "sump pump installation oakville",
  "secondaryKeywords": "sump pump repair oakville, sump pump replacement oakville, sump pump service oakville",
  "targetArea": "Oakville, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "300.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.5",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "105.0",
  "pageTitle": "Sump Pump Installation Ottawa | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-ottawa",
  "primaryKeyword": "sump pump installation ottawa",
  "secondaryKeywords": "sump pump repair ottawa, sump pump replacement ottawa, sump pump service ottawa",
  "targetArea": "Ottawa, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "0.0",
  "cpc": "7.0",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "106.0",
  "pageTitle": "Sump Pump Installation Scarborough | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-scarborough",
  "primaryKeyword": "sump pump installation scarborough",
  "secondaryKeywords": "sump pump repair scarborough, sump pump replacement scarborough, sump pump service scarborough",
  "targetArea": "Scarborough, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "107.0",
  "pageTitle": "Sump Pump Installation Mississauga | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-mississauga",
  "primaryKeyword": "sump pump installation mississauga",
  "secondaryKeywords": "sump pump repair mississauga, sump pump replacement mississauga, sump pump service mississauga",
  "targetArea": "Mississauga, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "108.0",
  "pageTitle": "Sump Pump Installation Burlington | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-burlington",
  "primaryKeyword": "sump pump installation burlington",
  "secondaryKeywords": "sump pump repair burlington, sump pump replacement burlington, sump pump service burlington",
  "targetArea": "Burlington, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "109.0",
  "pageTitle": "Sump Pump Installation Brampton | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-brampton",
  "primaryKeyword": "sump pump installation brampton",
  "secondaryKeywords": "sump pump repair brampton, sump pump replacement brampton, sump pump service brampton",
  "targetArea": "Brampton, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "110.0",
  "pageTitle": "Sump Pump Installation Markham | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-markham",
  "primaryKeyword": "sump pump installation markham",
  "secondaryKeywords": "sump pump repair markham, sump pump replacement markham, sump pump service markham",
  "targetArea": "Markham, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "111.0",
  "pageTitle": "Sump Pump Installation Vaughan | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-vaughan",
  "primaryKeyword": "sump pump installation vaughan",
  "secondaryKeywords": "sump pump repair vaughan, sump pump replacement vaughan, sump pump service vaughan",
  "targetArea": "Vaughan, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "112.0",
  "pageTitle": "Sump Pump Installation Oshawa | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-oshawa",
  "primaryKeyword": "sump pump installation oshawa",
  "secondaryKeywords": "sump pump repair oshawa, sump pump replacement oshawa, sump pump service oshawa",
  "targetArea": "Oshawa, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "113.0",
  "pageTitle": "Sump Pump Installation Whitby | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-whitby",
  "primaryKeyword": "sump pump installation whitby",
  "secondaryKeywords": "sump pump repair whitby, sump pump replacement whitby, sump pump service whitby",
  "targetArea": "Whitby, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "114.0",
  "pageTitle": "Sump Pump Installation Milton | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-milton",
  "primaryKeyword": "sump pump installation milton",
  "secondaryKeywords": "sump pump repair milton, sump pump replacement milton, sump pump service milton",
  "targetArea": "Milton, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "115.0",
  "pageTitle": "Sump Pump Installation Newmarket | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-newmarket",
  "primaryKeyword": "sump pump installation newmarket",
  "secondaryKeywords": "sump pump repair newmarket, sump pump replacement newmarket, sump pump service newmarket",
  "targetArea": "Newmarket, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "116.0",
  "pageTitle": "Sump Pump Installation Aurora | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-aurora",
  "primaryKeyword": "sump pump installation aurora",
  "secondaryKeywords": "sump pump repair aurora, sump pump replacement aurora, sump pump service aurora",
  "targetArea": "Aurora, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "117.0",
  "pageTitle": "Sump Pump Installation North York | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-north-york",
  "primaryKeyword": "sump pump installation north york",
  "secondaryKeywords": "sump pump repair north york, sump pump replacement north york, sump pump service north york",
  "targetArea": "North York, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "5.0",
  "priority": "Top Priority",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "118.0",
  "pageTitle": "Sump Pump Installation Richmond Hill | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-richmond-hill",
  "primaryKeyword": "sump pump installation richmond hill",
  "secondaryKeywords": "sump pump repair richmond hill, sump pump replacement richmond hill, sump pump service richmond hill",
  "targetArea": "Richmond Hill, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "119.0",
  "pageTitle": "Sump Pump Installation Pickering | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-pickering",
  "primaryKeyword": "sump pump installation pickering",
  "secondaryKeywords": "sump pump repair pickering, sump pump replacement pickering, sump pump service pickering",
  "targetArea": "Pickering, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "120.0",
  "pageTitle": "Sump Pump Installation Ajax | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-ajax",
  "primaryKeyword": "sump pump installation ajax",
  "secondaryKeywords": "sump pump repair ajax, sump pump replacement ajax, sump pump service ajax",
  "targetArea": "Ajax, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "121.0",
  "pageTitle": "Sump Pump Repair Bowmanville | Same Day Service, Call Now",
  "pageSlug": "/sump-pump-repair-bowmanville",
  "primaryKeyword": "sump pump repair bowmanville",
  "secondaryKeywords": "sump pump installation bowmanville, sump pump replacement bowmanville, sump pump service bowmanville",
  "targetArea": "Bowmanville, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "122.0",
  "pageTitle": "Sump Pump Installation Etobicoke | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-etobicoke",
  "primaryKeyword": "sump pump installation etobicoke",
  "secondaryKeywords": "sump pump repair etobicoke, sump pump replacement etobicoke, sump pump service etobicoke",
  "targetArea": "Etobicoke, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "123.0",
  "pageTitle": "Sump Pump Installation Hamilton | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-hamilton",
  "primaryKeyword": "sump pump installation hamilton",
  "secondaryKeywords": "sump pump repair hamilton, sump pump replacement hamilton, sump pump service hamilton",
  "targetArea": "Hamilton, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "124.0",
  "pageTitle": "Sump Pump Installation London | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-london",
  "primaryKeyword": "sump pump installation london",
  "secondaryKeywords": "sump pump repair london, sump pump replacement london, sump pump service london",
  "targetArea": "London, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "125.0",
  "pageTitle": "Sump Pump Installation Windsor | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-windsor",
  "primaryKeyword": "sump pump installation windsor",
  "secondaryKeywords": "sump pump repair windsor, sump pump replacement windsor, sump pump service windsor",
  "targetArea": "Windsor, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "126.0",
  "pageTitle": "Sump Pump Installation Barrie | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-barrie",
  "primaryKeyword": "sump pump installation barrie",
  "secondaryKeywords": "sump pump repair barrie, sump pump replacement barrie, sump pump service barrie",
  "targetArea": "Barrie, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "127.0",
  "pageTitle": "Sump Pump Installation Kitchener | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-kitchener",
  "primaryKeyword": "sump pump installation kitchener",
  "secondaryKeywords": "sump pump repair kitchener, sump pump replacement kitchener, sump pump service kitchener",
  "targetArea": "Kitchener, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "128.0",
  "pageTitle": "Sump Pump Installation Waterloo | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-waterloo",
  "primaryKeyword": "sump pump installation waterloo",
  "secondaryKeywords": "sump pump repair waterloo, sump pump replacement waterloo, sump pump service waterloo",
  "targetArea": "Waterloo, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "129.0",
  "pageTitle": "Sump Pump Installation Cambridge | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-cambridge",
  "primaryKeyword": "sump pump installation cambridge",
  "secondaryKeywords": "sump pump repair cambridge, sump pump replacement cambridge, sump pump service cambridge",
  "targetArea": "Cambridge, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "130.0",
  "pageTitle": "Sump Pump Installation Guelph | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-guelph",
  "primaryKeyword": "sump pump installation guelph",
  "secondaryKeywords": "sump pump repair guelph, sump pump replacement guelph, sump pump service guelph",
  "targetArea": "Guelph, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "131.0",
  "pageTitle": "Sump Pump Installation Brantford | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-brantford",
  "primaryKeyword": "sump pump installation brantford",
  "secondaryKeywords": "sump pump repair brantford, sump pump replacement brantford, sump pump service brantford",
  "targetArea": "Brantford, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "132.0",
  "pageTitle": "Sump Pump Installation St Catharines | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-st-catharines",
  "primaryKeyword": "sump pump installation st catharines",
  "secondaryKeywords": "sump pump repair st catharines, sump pump replacement st catharines, sump pump service st catharines",
  "targetArea": "St Catharines, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "133.0",
  "pageTitle": "Sump Pump Installation Niagara Falls | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-niagara-falls",
  "primaryKeyword": "sump pump installation niagara falls",
  "secondaryKeywords": "sump pump repair niagara falls, sump pump replacement niagara falls, sump pump service niagara falls",
  "targetArea": "Niagara Falls, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "134.0",
  "pageTitle": "Sump Pump Installation Welland | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-welland",
  "primaryKeyword": "sump pump installation welland",
  "secondaryKeywords": "sump pump repair welland, sump pump replacement welland, sump pump service welland",
  "targetArea": "Welland, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "135.0",
  "pageTitle": "Sump Pump Installation Thorold | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-thorold",
  "primaryKeyword": "sump pump installation thorold",
  "secondaryKeywords": "sump pump repair thorold, sump pump replacement thorold, sump pump service thorold",
  "targetArea": "Thorold, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "136.0",
  "pageTitle": "Sump Pump Installation Peterborough | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-peterborough",
  "primaryKeyword": "sump pump installation peterborough",
  "secondaryKeywords": "sump pump repair peterborough, sump pump replacement peterborough, sump pump service peterborough",
  "targetArea": "Peterborough, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "137.0",
  "pageTitle": "Sump Pump Installation Kingston | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-kingston",
  "primaryKeyword": "sump pump installation kingston",
  "secondaryKeywords": "sump pump repair kingston, sump pump replacement kingston, sump pump service kingston",
  "targetArea": "Kingston, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "138.0",
  "pageTitle": "Sump Pump Installation Brockville | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-brockville",
  "primaryKeyword": "sump pump installation brockville",
  "secondaryKeywords": "sump pump repair brockville, sump pump replacement brockville, sump pump service brockville",
  "targetArea": "Brockville, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "139.0",
  "pageTitle": "Sump Pump Replacement Greater Napanee | Install and Repair Service",
  "pageSlug": "/sump-pump-replacement-greater-napanee",
  "primaryKeyword": "sump pump replacement greater napanee",
  "secondaryKeywords": "sump pump installation greater napanee, sump pump repair greater napanee, sump pump service greater napanee",
  "targetArea": "Greater Napanee, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "100.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "140.0",
  "pageTitle": "Sump Pump Installation Gananoque | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-gananoque",
  "primaryKeyword": "sump pump installation gananoque",
  "secondaryKeywords": "sump pump repair gananoque, sump pump replacement gananoque, sump pump service gananoque",
  "targetArea": "Gananoque, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "141.0",
  "pageTitle": "Sump Pump Installation Cornwall | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-cornwall",
  "primaryKeyword": "sump pump installation cornwall",
  "secondaryKeywords": "sump pump repair cornwall, sump pump replacement cornwall, sump pump service cornwall",
  "targetArea": "Cornwall, ON",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "142.0",
  "pageTitle": "Sump Pump Installation Montreal | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-montreal",
  "primaryKeyword": "sump pump installation montreal",
  "secondaryKeywords": "sump pump repair montreal, sump pump replacement montreal, sump pump service montreal",
  "targetArea": "Montreal, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.9",
  "priority": "Medium",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "143.0",
  "pageTitle": "Sump Pump Installation Laval | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-laval",
  "primaryKeyword": "sump pump installation laval",
  "secondaryKeywords": "sump pump repair laval, sump pump replacement laval, sump pump service laval",
  "targetArea": "Laval, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "144.0",
  "pageTitle": "Sump Pump Installation Saint-Lambert | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-saint-lambert",
  "primaryKeyword": "sump pump installation saint-lambert",
  "secondaryKeywords": "sump pump repair saint-lambert, sump pump replacement saint-lambert, sump pump service saint-lambert",
  "targetArea": "Saint-Lambert, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "145.0",
  "pageTitle": "Sump Pump Installation Brossard | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-brossard",
  "primaryKeyword": "sump pump installation brossard",
  "secondaryKeywords": "sump pump repair brossard, sump pump replacement brossard, sump pump service brossard",
  "targetArea": "Brossard, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "146.0",
  "pageTitle": "Sump Pump Installation Chateauguay | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-chateauguay",
  "primaryKeyword": "sump pump installation chateauguay",
  "secondaryKeywords": "sump pump repair chateauguay, sump pump replacement chateauguay, sump pump service chateauguay",
  "targetArea": "Chateauguay, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "70.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "147.0",
  "pageTitle": "Sump Pump Installation Longueuil | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-longueuil",
  "primaryKeyword": "sump pump installation longueuil",
  "secondaryKeywords": "sump pump repair longueuil, sump pump replacement longueuil, sump pump service longueuil",
  "targetArea": "Longueuil, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "148.0",
  "pageTitle": "Sump Pump Installation Gatineau | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-gatineau",
  "primaryKeyword": "sump pump installation gatineau",
  "secondaryKeywords": "sump pump repair gatineau, sump pump replacement gatineau, sump pump service gatineau",
  "targetArea": "Gatineau, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "60.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "149.0",
  "pageTitle": "Sump Pump Installation Quebec City | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-quebec-city",
  "primaryKeyword": "sump pump installation quebec city",
  "secondaryKeywords": "sump pump repair quebec city, sump pump replacement quebec city, sump pump service quebec city",
  "targetArea": "Quebec City, QC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "150.0",
  "pageTitle": "Sump Pump Installation Vancouver | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-vancouver",
  "primaryKeyword": "sump pump installation vancouver",
  "secondaryKeywords": "sump pump repair vancouver, sump pump replacement vancouver, sump pump service vancouver",
  "targetArea": "Vancouver, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "90.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "151.0",
  "pageTitle": "Sump Pump Installation Surrey | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-surrey",
  "primaryKeyword": "sump pump installation surrey",
  "secondaryKeywords": "sump pump repair surrey, sump pump replacement surrey, sump pump service surrey",
  "targetArea": "Surrey, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "152.0",
  "pageTitle": "Sump Pump Installation Burnaby | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-burnaby",
  "primaryKeyword": "sump pump installation burnaby",
  "secondaryKeywords": "sump pump repair burnaby, sump pump replacement burnaby, sump pump service burnaby",
  "targetArea": "Burnaby, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "153.0",
  "pageTitle": "Sump Pump Installation Coquitlam | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-coquitlam",
  "primaryKeyword": "sump pump installation coquitlam",
  "secondaryKeywords": "sump pump repair coquitlam, sump pump replacement coquitlam, sump pump service coquitlam",
  "targetArea": "Coquitlam, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "154.0",
  "pageTitle": "Sump Pump Installation Victoria | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-victoria",
  "primaryKeyword": "sump pump installation victoria",
  "secondaryKeywords": "sump pump repair victoria, sump pump replacement victoria, sump pump service victoria",
  "targetArea": "Victoria, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "155.0",
  "pageTitle": "Sump Pump Installation Kelowna | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-kelowna",
  "primaryKeyword": "sump pump installation kelowna",
  "secondaryKeywords": "sump pump repair kelowna, sump pump replacement kelowna, sump pump service kelowna",
  "targetArea": "Kelowna, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "156.0",
  "pageTitle": "Sump Pump Installation Richmond | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-richmond",
  "primaryKeyword": "sump pump installation richmond",
  "secondaryKeywords": "sump pump repair richmond, sump pump replacement richmond, sump pump service richmond",
  "targetArea": "Richmond, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "157.0",
  "pageTitle": "Sump Pump Installation Port Moody | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-port-moody",
  "primaryKeyword": "sump pump installation port moody",
  "secondaryKeywords": "sump pump repair port moody, sump pump replacement port moody, sump pump service port moody",
  "targetArea": "Port Moody, BC",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "20.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "158.0",
  "pageTitle": "Sump Pump Installation Winnipeg | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-winnipeg",
  "primaryKeyword": "sump pump installation winnipeg",
  "secondaryKeywords": "sump pump repair winnipeg, sump pump replacement winnipeg, sump pump service winnipeg",
  "targetArea": "Winnipeg, MB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "0.0",
  "cpc": "1.7",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "159.0",
  "pageTitle": "Sump Pump Installation Edmonton | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-edmonton",
  "primaryKeyword": "sump pump installation edmonton",
  "secondaryKeywords": "sump pump repair edmonton, sump pump replacement edmonton, sump pump service edmonton",
  "targetArea": "Edmonton, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "200.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "160.0",
  "pageTitle": "Sump Pump Installation Calgary | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-calgary",
  "primaryKeyword": "sump pump installation calgary",
  "secondaryKeywords": "sump pump repair calgary, sump pump replacement calgary, sump pump service calgary",
  "targetArea": "Calgary, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "150.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "161.0",
  "pageTitle": "Sump Pump Installation Leduc | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-leduc",
  "primaryKeyword": "sump pump installation leduc",
  "secondaryKeywords": "sump pump repair leduc, sump pump replacement leduc, sump pump service leduc",
  "targetArea": "Leduc, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "30.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "162.0",
  "pageTitle": "Sump Pump Installation Nisku | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-nisku",
  "primaryKeyword": "sump pump installation nisku",
  "secondaryKeywords": "sump pump repair nisku, sump pump replacement nisku, sump pump service nisku",
  "targetArea": "Nisku, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "163.0",
  "pageTitle": "Sump Pump Installation Spruce Grove | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-spruce-grove",
  "primaryKeyword": "sump pump installation spruce grove",
  "secondaryKeywords": "sump pump repair spruce grove, sump pump replacement spruce grove, sump pump service spruce grove",
  "targetArea": "Spruce Grove, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "20.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "164.0",
  "pageTitle": "Sump Pump Installation St Albert | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-st-albert",
  "primaryKeyword": "sump pump installation st albert",
  "secondaryKeywords": "sump pump repair st albert, sump pump replacement st albert, sump pump service st albert",
  "targetArea": "St Albert, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "4.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "165.0",
  "pageTitle": "Sump Pump Installation Red Deer | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-red-deer",
  "primaryKeyword": "sump pump installation red deer",
  "secondaryKeywords": "sump pump repair red deer, sump pump replacement red deer, sump pump service red deer",
  "targetArea": "Red Deer, AB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "3.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "166.0",
  "pageTitle": "Sump Pump Installation Saskatoon | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-saskatoon",
  "primaryKeyword": "sump pump installation saskatoon",
  "secondaryKeywords": "sump pump repair saskatoon, sump pump replacement saskatoon, sump pump service saskatoon",
  "targetArea": "Saskatoon, SK",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "167.0",
  "pageTitle": "Sump Pump Installation Regina | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-regina",
  "primaryKeyword": "sump pump installation regina",
  "secondaryKeywords": "sump pump repair regina, sump pump replacement regina, sump pump service regina",
  "targetArea": "Regina, SK",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "50.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.5",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
},
{
  "id": "168.0",
  "pageTitle": "Sump Pump Installation Brandon | Repair and Replacement",
  "pageSlug": "/sump-pump-installation-brandon",
  "primaryKeyword": "sump pump installation brandon",
  "secondaryKeywords": "sump pump repair brandon, sump pump replacement brandon, sump pump service brandon",
  "targetArea": "Brandon, MB",
  "pageType": "City Service",
  "searchIntent": "Local Trans.",
  "volumePerMonth": "40.0",
  "keywordDifficulty": "0.0",
  "cpc": "2.0",
  "priority": "High",
  "ctaStrategy": "Call 1-888-793-2080"
}
] as const;
