export const RAW_PAGES = [
  {
    "id": "1.0",
    "pageTitle": "Mobile Home Plumbing Services in Canada | Repairs and Leaks",
    "pageSlug": "/mobile-home-plumbing",
    "primaryKeyword": "mobile home plumbing",
    "secondaryKeywords": "mobile home plumbing repair, mobile home plumbing problems, plumbing under mobile home, mobile home plumbing layout",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Commercial",
    "volumePerMonth": "60.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "2.0",
    "pageTitle": "Mobile Home Plumber | Same-Day Repairs and Re-Pipes",
    "pageSlug": "/mobile-home-plumber",
    "primaryKeyword": "mobile home plumber",
    "secondaryKeywords": "mobile home plumber near me, plumber for mobile home, plumber mobile home, mobile home plumbing repair near me",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "60.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "3.0",
    "pageTitle": "Manufactured Home Plumber | Plumbing Repair Specialists",
    "pageSlug": "/manufactured-home-plumber",
    "primaryKeyword": "manufactured home plumbing",
    "secondaryKeywords": "manufactured home plumber, modular home plumbing, manufactured home plumbing repair, plumber for manufactured home",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "4.0",
    "pageTitle": "Mobile and Manufactured Home Water Damage Restoration",
    "pageSlug": "/mobile-home-water-damage-restoration",
    "primaryKeyword": "mobile home water damage",
    "secondaryKeywords": "mobile home water damage restoration, water damage in mobile home, mobile home water damage floor, mobile home wall water damage",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "5.0",
    "pageTitle": "RV and Motorhome Plumber | Mobile Plumbing Repair",
    "pageSlug": "/rv-plumber",
    "primaryKeyword": "rv plumber",
    "secondaryKeywords": "rv plumber near me, mobile rv plumber, rv plumbing repair, motorhome plumbing, plumber for rv",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "6.0",
    "pageTitle": "RV and Trailer Water Damage Repair | Leak and Flood Fix",
    "pageSlug": "/rv-water-damage-repair",
    "primaryKeyword": "rv water damage repair",
    "secondaryKeywords": "trailer water damage repair, camper water damage, travel trailer water damage repair, rv slide out water damage repair",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "7.0",
    "pageTitle": "Calgary Mobile Home Plumber | Repairs and Re-Pipes",
    "pageSlug": "/mobile-home-plumber-calgary",
    "primaryKeyword": "calgary mobile home plumber",
    "secondaryKeywords": "calgary mobile home plumbing, mobile home plumber calgary, mobile home plumbing calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "50.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "8.0",
    "pageTitle": "Edmonton Mobile Home Plumber | Plumbing Repair Service",
    "pageSlug": "/mobile-home-plumber-edmonton",
    "primaryKeyword": "edmonton mobile home plumbing",
    "secondaryKeywords": "mobile home plumber edmonton, mobile home plumbing edmonton, manufactured home plumber edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "9.0",
    "pageTitle": "Red Deer Mobile Home Plumber | Manufactured Home Repairs",
    "pageSlug": "/mobile-home-plumber-red-deer",
    "primaryKeyword": "red deer mobile home plumber",
    "secondaryKeywords": "mobile home plumbing red deer, manufactured home plumber red deer, mobile home plumber central alberta",
    "targetArea": "Red Deer, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "10.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "10.0",
    "pageTitle": "Emergency Plumber | 24/7 Same-Day Service Across Canada",
    "pageSlug": "/emergency-plumber",
    "primaryKeyword": "emergency plumber",
    "secondaryKeywords": "emergency plumber service, plumber emergency, emergency plumbing, 24 hour emergency plumber",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "4800.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "11.0",
    "pageTitle": "Emergency Plumber Near Me | 24/7 Local Plumbing Help",
    "pageSlug": "/emergency-plumber-near-me",
    "primaryKeyword": "emergency plumber near me",
    "secondaryKeywords": "24/7 emergency plumber, emergency plumber near me open now, local emergency plumber, plumber near me emergency",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "3900.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.5",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "12.0",
    "pageTitle": "24/7 Emergency Plumber | Burst Pipes, Leaks and Floods",
    "pageSlug": "/24-7-emergency-plumber",
    "primaryKeyword": "24/7 emergency plumber",
    "secondaryKeywords": "24 hour plumber, after hours plumber, overnight emergency plumber, weekend emergency plumber",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "13.0",
    "pageTitle": "Burst Pipe Repair | Emergency Pipe and Leak Service",
    "pageSlug": "/burst-pipe-repair",
    "primaryKeyword": "burst pipe repair",
    "secondaryKeywords": "burst pipe plumber, frozen pipe repair, emergency pipe repair, leaking pipe repair, burst water pipe",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "14.0",
    "pageTitle": "Water Damage Restoration | 24/7 Flood and Leak Cleanup",
    "pageSlug": "/water-damage-restoration",
    "primaryKeyword": "water damage restoration",
    "secondaryKeywords": "water damage restoration service, emergency water damage restoration, flood damage restoration, water damage cleanup",
    "targetArea": "Canada (National)",
    "pageType": "Service Pillar",
    "searchIntent": "Transactional",
    "volumePerMonth": "2300.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "15.0",
    "pageTitle": "Water Damage Restoration Near Me | Local Flood Cleanup",
    "pageSlug": "/water-damage-restoration-near-me",
    "primaryKeyword": "water damage restoration near me",
    "secondaryKeywords": "water damage restoration services near me, water damage restoration companies near me, water damage company near me",
    "targetArea": "Canada (National)",
    "pageType": "Near Me Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "900.0",
    "keywordDifficulty": "3.0",
    "cpc": "2.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "16.0",
    "pageTitle": "Emergency Water Damage Restoration Company | 24/7 Help",
    "pageSlug": "/emergency-water-damage-restoration",
    "primaryKeyword": "emergency water damage restoration company",
    "secondaryKeywords": "emergency water damage restoration services, 24 hour water damage restoration, emergency flood cleanup, water extraction service",
    "targetArea": "Canada (National)",
    "pageType": "Emergency Landing",
    "searchIntent": "Transactional",
    "volumePerMonth": "400.0",
    "keywordDifficulty": "3.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "17.0",
    "pageTitle": "Emergency Plumber Ottawa | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-ottawa",
    "primaryKeyword": "emergency plumber ottawa",
    "secondaryKeywords": "24 hour plumber ottawa, ottawa emergency plumbing, burst pipe plumber ottawa, after hours plumber ottawa",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "0.0",
    "cpc": "7.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "18.0",
    "pageTitle": "Emergency Plumber Mississauga | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-mississauga",
    "primaryKeyword": "emergency plumber mississauga",
    "secondaryKeywords": "24 hour plumber mississauga, mississauga emergency plumbing, burst pipe mississauga, weekend plumber mississauga",
    "targetArea": "Mississauga, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "0.0",
    "cpc": "13.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "19.0",
    "pageTitle": "Emergency Plumber Hamilton | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-hamilton",
    "primaryKeyword": "emergency plumber hamilton",
    "secondaryKeywords": "24 hour plumber hamilton, hamilton emergency plumbing, burst pipe hamilton, after hours plumber hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "20.0",
    "pageTitle": "Emergency Plumber Kingston | 24/7 Plumbing Repairs",
    "pageSlug": "/emergency-plumber-kingston",
    "primaryKeyword": "emergency plumber kingston",
    "secondaryKeywords": "kingston emergency plumber, emergency plumber kingston ontario, 24 hour plumber kingston, burst pipe kingston",
    "targetArea": "Kingston, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "400.0",
    "keywordDifficulty": "0.0",
    "cpc": "8.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "21.0",
    "pageTitle": "Emergency Plumber Kitchener | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-kitchener",
    "primaryKeyword": "emergency plumber kitchener",
    "secondaryKeywords": "24 hour plumber kitchener, kitchener waterloo emergency plumber, burst pipe kitchener, after hours plumber kitchener",
    "targetArea": "Kitchener, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "17.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "22.0",
    "pageTitle": "Emergency Plumber Oshawa | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-oshawa",
    "primaryKeyword": "emergency plumber oshawa",
    "secondaryKeywords": "24 hour plumber oshawa, oshawa emergency plumbing, burst pipe oshawa, durham emergency plumber",
    "targetArea": "Oshawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "15.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "23.0",
    "pageTitle": "Emergency Plumber Burlington | 24/7 Plumbing Repairs",
    "pageSlug": "/emergency-plumber-burlington",
    "primaryKeyword": "emergency plumber burlington",
    "secondaryKeywords": "24 hour plumber burlington, burlington emergency plumbing, burst pipe burlington, after hours plumber burlington",
    "targetArea": "Burlington, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "16.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "24.0",
    "pageTitle": "Emergency Plumber Milton | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-milton",
    "primaryKeyword": "emergency plumber milton",
    "secondaryKeywords": "24 hour plumber milton, milton emergency plumbing, burst pipe milton, after hours plumber milton",
    "targetArea": "Milton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "13.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "25.0",
    "pageTitle": "Emergency Plumber Etobicoke | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-etobicoke",
    "primaryKeyword": "emergency plumber etobicoke",
    "secondaryKeywords": "24 hour plumber etobicoke, etobicoke emergency plumbing, burst pipe etobicoke, west toronto emergency plumber",
    "targetArea": "Etobicoke, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "12.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "26.0",
    "pageTitle": "Emergency Plumber London Ontario | 24/7 Plumbing",
    "pageSlug": "/emergency-plumber-london-ontario",
    "primaryKeyword": "emergency plumber london ontario",
    "secondaryKeywords": "emergency plumber london, 24 hour plumber london ontario, burst pipe london ontario, after hours plumber london",
    "targetArea": "London, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "27.0",
    "pageTitle": "Emergency Plumber Ajax | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-ajax",
    "primaryKeyword": "emergency plumber ajax",
    "secondaryKeywords": "24 hour plumber ajax, ajax emergency plumbing, burst pipe ajax, pickering emergency plumber",
    "targetArea": "Ajax, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "10.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "28.0",
    "pageTitle": "Emergency Plumber Toronto | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-toronto",
    "primaryKeyword": "emergency plumber toronto",
    "secondaryKeywords": "24 hour plumber toronto, toronto emergency plumbing, burst pipe toronto, after hours plumber toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "34.0",
    "cpc": "12.0",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "29.0",
    "pageTitle": "Emergency Plumber Barrie | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-barrie",
    "primaryKeyword": "emergency plumber barrie",
    "secondaryKeywords": "24 hour plumber barrie, barrie emergency plumbing, burst pipe barrie, after hours plumber barrie",
    "targetArea": "Barrie, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "4.0",
    "cpc": "12.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "30.0",
    "pageTitle": "Emergency Plumber Brampton | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-brampton",
    "primaryKeyword": "emergency plumber brampton",
    "secondaryKeywords": "24 hour plumber brampton, brampton emergency plumbing, burst pipe brampton, after hours plumber brampton",
    "targetArea": "Brampton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "13.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "31.0",
    "pageTitle": "Emergency Plumber Markham | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-markham",
    "primaryKeyword": "emergency plumber markham",
    "secondaryKeywords": "24 hour plumber markham, markham emergency plumbing, burst pipe markham, after hours plumber markham",
    "targetArea": "Markham, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "15.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "32.0",
    "pageTitle": "Emergency Plumber Vaughan | 24/7 Plumbing Repairs",
    "pageSlug": "/emergency-plumber-vaughan",
    "primaryKeyword": "emergency plumber vaughan",
    "secondaryKeywords": "24 hour plumber vaughan, vaughan emergency plumbing, burst pipe vaughan, after hours plumber vaughan",
    "targetArea": "Vaughan, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "0.0",
    "cpc": "15.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "33.0",
    "pageTitle": "Emergency Plumber Guelph | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-guelph",
    "primaryKeyword": "emergency plumber guelph",
    "secondaryKeywords": "24 hour plumber guelph, guelph emergency plumbing, burst pipe guelph, after hours plumber guelph",
    "targetArea": "Guelph, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "9.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "34.0",
    "pageTitle": "Emergency Plumber Windsor | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-windsor",
    "primaryKeyword": "emergency plumber windsor",
    "secondaryKeywords": "24 hour plumber windsor, windsor emergency plumbing, burst pipe windsor, after hours plumber windsor",
    "targetArea": "Windsor, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "4.0",
    "cpc": "4.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "35.0",
    "pageTitle": "Emergency Plumber Bowmanville | 24/7 Plumbing",
    "pageSlug": "/emergency-plumber-bowmanville",
    "primaryKeyword": "emergency plumber bowmanville",
    "secondaryKeywords": "24 hour plumber bowmanville, bowmanville emergency plumbing, burst pipe bowmanville, after hours plumber bowmanville",
    "targetArea": "Bowmanville, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "0.0",
    "cpc": "10.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "36.0",
    "pageTitle": "Emergency Plumber Sudbury | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-sudbury",
    "primaryKeyword": "emergency plumber sudbury",
    "secondaryKeywords": "24 hour plumber sudbury, sudbury emergency plumbing, burst pipe sudbury, after hours plumber sudbury",
    "targetArea": "Sudbury, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "5.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "37.0",
    "pageTitle": "Emergency Plumber Vancouver | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-vancouver",
    "primaryKeyword": "emergency plumber vancouver",
    "secondaryKeywords": "vancouver emergency plumber, 24 hour plumber vancouver, burst pipe vancouver, after hours plumber vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "6.0",
    "cpc": "14.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "38.0",
    "pageTitle": "Emergency Plumber North Vancouver | 24/7 Plumbing",
    "pageSlug": "/emergency-plumber-north-vancouver",
    "primaryKeyword": "emergency plumber north vancouver",
    "secondaryKeywords": "24 hour plumber north vancouver, north shore emergency plumber, burst pipe north vancouver, west vancouver plumber",
    "targetArea": "North Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "20.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "39.0",
    "pageTitle": "Emergency Plumber Victoria | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-victoria",
    "primaryKeyword": "emergency plumber victoria",
    "secondaryKeywords": "24 hour plumber victoria bc, victoria emergency plumbing, burst pipe victoria, after hours plumber victoria",
    "targetArea": "Victoria, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "2.0",
    "cpc": "17.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "40.0",
    "pageTitle": "Emergency Plumber Langley | 24/7 Plumbing Repairs",
    "pageSlug": "/emergency-plumber-langley",
    "primaryKeyword": "emergency plumber langley",
    "secondaryKeywords": "24 hour plumber langley, langley emergency plumbing, burst pipe langley, fraser valley emergency plumber",
    "targetArea": "Langley, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "15.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "41.0",
    "pageTitle": "Emergency Plumber Kamloops | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-kamloops",
    "primaryKeyword": "emergency plumber kamloops",
    "secondaryKeywords": "24 hour plumber kamloops, kamloops emergency plumbing, burst pipe kamloops, after hours plumber kamloops",
    "targetArea": "Kamloops, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "12.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "42.0",
    "pageTitle": "Emergency Plumber Surrey | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-surrey",
    "primaryKeyword": "emergency plumber surrey",
    "secondaryKeywords": "24 hour plumber surrey, surrey emergency plumbing, burst pipe surrey, after hours plumber surrey",
    "targetArea": "Surrey, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "9.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "43.0",
    "pageTitle": "Emergency Plumber Burnaby | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-burnaby",
    "primaryKeyword": "emergency plumber burnaby",
    "secondaryKeywords": "24 hour plumber burnaby, burnaby emergency plumbing, burst pipe burnaby, after hours plumber burnaby",
    "targetArea": "Burnaby, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "5.0",
    "cpc": "16.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "44.0",
    "pageTitle": "Emergency Plumber Kelowna | 24/7 Plumbing Repairs",
    "pageSlug": "/emergency-plumber-kelowna",
    "primaryKeyword": "emergency plumber kelowna",
    "secondaryKeywords": "24 hour plumber kelowna, kelowna emergency plumbing, burst pipe kelowna, after hours plumber kelowna",
    "targetArea": "Kelowna, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "14.0",
    "cpc": "11.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "45.0",
    "pageTitle": "Emergency Plumber Calgary | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-calgary",
    "primaryKeyword": "emergency plumber calgary",
    "secondaryKeywords": "calgary emergency plumber, 24 hour plumber calgary, burst pipe calgary, after hours plumber calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "0.0",
    "cpc": "9.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "46.0",
    "pageTitle": "Emergency Plumber Edmonton | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-edmonton",
    "primaryKeyword": "emergency plumber edmonton",
    "secondaryKeywords": "edmonton emergency plumber, 24 hour plumber edmonton, burst pipe edmonton, after hours plumber edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "8.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "47.0",
    "pageTitle": "Emergency Plumber Winnipeg | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-winnipeg",
    "primaryKeyword": "emergency plumber winnipeg",
    "secondaryKeywords": "24 hour plumber winnipeg, winnipeg emergency plumbing, burst pipe winnipeg, after hours plumber winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "48.0",
    "pageTitle": "Emergency Plumber Saskatoon | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-saskatoon",
    "primaryKeyword": "emergency plumber saskatoon",
    "secondaryKeywords": "24 hour plumber saskatoon, saskatoon emergency plumbing, burst pipe saskatoon, after hours plumber saskatoon",
    "targetArea": "Saskatoon, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "60.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "49.0",
    "pageTitle": "Emergency Plumber Regina | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-regina",
    "primaryKeyword": "emergency plumber regina",
    "secondaryKeywords": "24 hour plumber regina, regina emergency plumbing, burst pipe regina, after hours plumber regina",
    "targetArea": "Regina, SK",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "50.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.0",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "50.0",
    "pageTitle": "Emergency Plumber Beaconsfield | 24/7 Plumbing",
    "pageSlug": "/emergency-plumber-beaconsfield",
    "primaryKeyword": "emergency plumber beaconsfield",
    "secondaryKeywords": "24 hour plumber beaconsfield, beaconsfield emergency plumbing, burst pipe beaconsfield, after hours plumber beaconsfield",
    "targetArea": "Beaconsfield, QC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "600.0",
    "keywordDifficulty": "0.0",
    "cpc": "7.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "51.0",
    "pageTitle": "Emergency Plumber Dollard-des-Ormeaux | 24/7 Plumbing",
    "pageSlug": "/emergency-plumber-dollard-des-ormeaux",
    "primaryKeyword": "emergency plumber dollard-des ormeaux",
    "secondaryKeywords": "24 hour plumber dollard-des-ormeaux, dollard-des-ormeaux emergency plumbing, burst pipe dollard-des-ormeaux, after hours plumber dollard-des-ormeaux",
    "targetArea": "Dollard-des-Ormeaux, QC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "350.0",
    "keywordDifficulty": "0.0",
    "cpc": "7.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "52.0",
    "pageTitle": "Emergency Plumber Kirkland | 24/7 Same-Day Plumber",
    "pageSlug": "/emergency-plumber-kirkland",
    "primaryKeyword": "emergency plumber kirkland",
    "secondaryKeywords": "24 hour plumber kirkland, kirkland emergency plumbing, burst pipe kirkland, after hours plumber kirkland",
    "targetArea": "Kirkland, QC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "0.0",
    "cpc": "7.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "53.0",
    "pageTitle": "Emergency Plumber Pierrefonds | 24/7 Plumbing Service",
    "pageSlug": "/emergency-plumber-pierrefonds",
    "primaryKeyword": "emergency plumber pierrefonds",
    "secondaryKeywords": "24 hour plumber pierrefonds, pierrefonds emergency plumbing, burst pipe pierrefonds, after hours plumber pierrefonds",
    "targetArea": "Pierrefonds, QC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "0.0",
    "cpc": "7.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "54.0",
    "pageTitle": "Emergency Plumber Halifax | 24/7 Same-Day Plumbing",
    "pageSlug": "/emergency-plumber-halifax",
    "primaryKeyword": "emergency plumber halifax",
    "secondaryKeywords": "24 hour plumber halifax, halifax emergency plumbing, burst pipe halifax, after hours plumber halifax",
    "targetArea": "Halifax, NS",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "4.0",
    "cpc": "1.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "55.0",
    "pageTitle": "Water Damage Restoration Vancouver | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-vancouver",
    "primaryKeyword": "water damage restoration vancouver",
    "secondaryKeywords": "flood restoration vancouver, water damage cleanup vancouver, emergency water removal vancouver, basement flood vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "3.0",
    "cpc": "4.5",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "56.0",
    "pageTitle": "Water Damage Restoration Calgary | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-calgary",
    "primaryKeyword": "water damage restoration calgary",
    "secondaryKeywords": "flood restoration calgary, water damage cleanup calgary, emergency water removal calgary, basement flood calgary",
    "targetArea": "Calgary, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "9.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "57.0",
    "pageTitle": "Water Damage Restoration Ottawa | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-ottawa",
    "primaryKeyword": "water damage restoration ottawa",
    "secondaryKeywords": "flood restoration ottawa, water damage cleanup ottawa, emergency water removal ottawa, basement flood ottawa",
    "targetArea": "Ottawa, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "5.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "58.0",
    "pageTitle": "Water Damage Restoration Edmonton | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-edmonton",
    "primaryKeyword": "water damage restoration edmonton",
    "secondaryKeywords": "flood restoration edmonton, water damage cleanup edmonton, emergency water removal edmonton, basement flood edmonton",
    "targetArea": "Edmonton, AB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "6.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "59.0",
    "pageTitle": "Water Damage Restoration Toronto | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-toronto",
    "primaryKeyword": "water damage restoration toronto",
    "secondaryKeywords": "flood restoration toronto, water damage cleanup toronto, emergency water removal toronto, basement flood toronto",
    "targetArea": "Toronto, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "17.0",
    "cpc": "9.0",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "60.0",
    "pageTitle": "Water Damage Restoration Mississauga | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-mississauga",
    "primaryKeyword": "water damage restoration mississauga",
    "secondaryKeywords": "flood restoration mississauga, water damage cleanup mississauga, emergency water removal mississauga, basement flood mississauga",
    "targetArea": "Mississauga, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "9.0",
    "cpc": "2.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "61.0",
    "pageTitle": "Water Damage Restoration Hamilton | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-hamilton",
    "primaryKeyword": "water damage restoration hamilton",
    "secondaryKeywords": "flood restoration hamilton, water damage cleanup hamilton, emergency water removal hamilton, basement flood hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "0.0",
    "cpc": "20.0",
    "priority": "Top Priority",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "62.0",
    "pageTitle": "Water Damage Restoration Winnipeg | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-winnipeg",
    "primaryKeyword": "water damage restoration winnipeg",
    "secondaryKeywords": "flood restoration winnipeg, water damage cleanup winnipeg, emergency water removal winnipeg, basement flood winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "63.0",
    "pageTitle": "Water Damage Restoration Kelowna | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-kelowna",
    "primaryKeyword": "water damage restoration kelowna",
    "secondaryKeywords": "flood restoration kelowna, water damage cleanup kelowna, emergency water removal kelowna, basement flood kelowna",
    "targetArea": "Kelowna, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "64.0",
    "pageTitle": "Water Damage Restoration Barrie | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-barrie",
    "primaryKeyword": "water damage restoration barrie",
    "secondaryKeywords": "flood restoration barrie, water damage cleanup barrie, emergency water removal barrie, basement flood barrie",
    "targetArea": "Barrie, ON",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "50.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "65.0",
    "pageTitle": "Water Damage Restoration Surrey | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-surrey",
    "primaryKeyword": "water damage restoration surrey",
    "secondaryKeywords": "flood restoration surrey, water damage cleanup surrey, emergency water removal surrey, basement flood surrey",
    "targetArea": "Surrey, BC",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "0.0",
    "cpc": "16.0",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "66.0",
    "pageTitle": "Water Damage Restoration Halifax | 24/7 Flood Cleanup",
    "pageSlug": "/water-damage-restoration-halifax",
    "primaryKeyword": "water damage restoration halifax",
    "secondaryKeywords": "flood restoration halifax, water damage cleanup halifax, emergency water removal halifax, basement flood halifax",
    "targetArea": "Halifax, NS",
    "pageType": "City Service Page",
    "searchIntent": "Local Transactional",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "0.0",
    "cpc": "3.0",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "67.0",
    "pageTitle": "Common Mobile Home Plumbing Problems and How to Fix Them",
    "pageSlug": "/mobile-home-plumbing-problems",
    "primaryKeyword": "mobile home plumbing problems",
    "secondaryKeywords": "mobile home plumbing repair, mobile home low water pressure, mobile home pipe leak, mobile home drain problems",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "80.0",
    "keywordDifficulty": "0.0",
    "cpc": "1.5",
    "priority": "High",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "68.0",
    "pageTitle": "How to Winterize Mobile Home Plumbing | Prevent Frozen Pipes",
    "pageSlug": "/winterize-mobile-home-plumbing",
    "primaryKeyword": "winterize mobile home plumbing",
    "secondaryKeywords": "mobile home frozen pipes, mobile home pipe insulation, prevent frozen pipes mobile home, mobile home winter plumbing",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "0.0",
    "cpc": "1.5",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "69.0",
    "pageTitle": "RV Water Damage Repair Cost | Pricing and Estimates Guide",
    "pageSlug": "/rv-water-damage-repair-cost",
    "primaryKeyword": "rv water damage repair cost",
    "secondaryKeywords": "rv water damage floor repair cost, rv slide out water damage repair cost, trailer water damage repair cost, camper water damage cost",
    "targetArea": "Canada (National)",
    "pageType": "Cost Guide",
    "searchIntent": "Commercial",
    "volumePerMonth": "90.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.0",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  },
  {
    "id": "70.0",
    "pageTitle": "Does Insurance Cover Water Damage on a Trailer or Camper?",
    "pageSlug": "/trailer-water-damage-insurance",
    "primaryKeyword": "does trailer insurance cover water damage",
    "secondaryKeywords": "does travel trailer insurance cover water damage, does camper insurance cover water damage, rv water damage insurance claim",
    "targetArea": "Canada (National)",
    "pageType": "Symptom Page",
    "searchIntent": "Informational",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.0",
    "priority": "Medium",
    "ctaStrategy": "Click to Call 1-888-609-7298"
  }
] as const;
